#!/usr/bin/perl -w

use strict;
BEGIN { push @INC, q{/home/keithw/rotisserie} }
require q{login.pl};
use HTML::Entities;
use POSIX;

print qq{Content-type: text/html\n\n};

print_header( q{Permission code to enroll in CS181/CS181W} );

my $dbh = &database;

my ( $sunetid, $display_name, $first_name, $class ) = login ( $dbh );

my $get_code = $dbh->prepare( q{SELECT code FROM codes WHERE sunetid = ?} ) or die qq{$DBI::errstr};

$get_code->execute( $sunetid ) or die qq{$DBI::errstr};

my $code = qq{(no code assigned)};

while ( my $data = $get_code->fetchrow_hashref ) {
  $code = $data->{ code };
}

print qq{<h4>Welcome to ${class}, ${first_name}! Your permission code to enroll is: <tt>${code}</tt> .</h4>};

&finish;
