#!/usr/bin/perl -w

use strict;
require q{login.pl};
use HTML::Entities;
use POSIX;

print qq{Content-type: text/html\n\n};

print <<END;
<!DOCTYPE html>
<html lang="en" style="height: 80%;">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="CS 181/181W: Computers, Ethics, and Public Policy">
    <link href="https://stanfordcs181.github.io/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://stanfordcs181.github.io/css/bootstrap-theme.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="https://stanfordcs181.github.io/stanford.png">

    <script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="/TrixCSS">
    <script type="text/javascript" src="/TrixJS"></script>
    <script type="text/javascript" src="/LetterJS"></script>
    <script type="text/javascript" src="/TextJS"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
  </head>

  <body role="document" style="height: 100%;">
    <div class="container" role="main" style="height: 100%;">
END

my $dbh = &database;

my ( $sunetid, $display_name, $first_name, $class ) = login ( $dbh );

die unless defined $sunetid;
die unless defined $class;

if ( $class ne q{staff} ) {
  print qq{<h4>This page is limited to CS181/181W staff.</h4>};
  &finish;
}

my $name = "";
my $essay = "";

while ( 1 ) {
  my $random_sunetid = $dbh->prepare( q{SELECT sunetid FROM users WHERE class != 'staff' ORDER BY random() LIMIT 1} ) or die qq{$DBI::errstr};
  $random_sunetid->execute() or die qq{$DBI::errstr};

  my $sunetid = $random_sunetid->fetchrow_hashref->{ sunetid };
  
  my $sunetid_to_essay = $dbh->prepare( q{SELECT contents, name FROM writing, hits WHERE assignment = ? AND writing.sunetid = ? AND hits.sunetid = writing.sunetid ORDER BY submitted DESC LIMIT 1} ) or die qq{$DBI::errstr};
  $sunetid_to_essay->execute( q{trolley}, $sunetid ) or die qq{$DBI::errstr};

  if ( my $data2 = $sunetid_to_essay->fetchrow_hashref ) {
    $name = $data2->{ name };
    $essay = $data2->{ contents };
    last;
  }
}

$sunetid = HTML::Entities::encode_entities( $sunetid );
$name = HTML::Entities::encode_entities( $name );

my $text2 = $essay;
$text2 =~ s{[ \t\n]+/}{ }g;
my $wordcount = scalar (split / +/, $text2);
$wordcount = 10 * int( $wordcount / 10.0 + 0.5 );

$essay =~ s{$name}{(name)}g;

print qq{<h4><span style="color: white;">${name}</span> <span class="text-muted">(about $wordcount words)</span></h4>};
print qq{<div class="well trix-content">$essay</div><p><hr><p>};

print q{</div></body>};
