#!/usr/bin/perl -w

use strict;
require q{login.pl};

print qq{Content-type: text/html\n\n};

print_header( q{Registration} );

my $dbh = &database;

my ( $sunetid, $display_name, $first_name, $class ) = login ( $dbh );

print qq{<h4>Welcome, $first_name (${class}).</h4>};
&finish;
