#!/usr/bin/perl -w

use strict;
require q{login.pl};
use HTML::Entities;
use POSIX;

print qq{Content-type: text/html\n\n};

print_header( q{First-day writing assignment (Therac 25)} );

my $dbh = &database;

my ( $sunetid, $display_name, $first_name, $class ) = login ( $dbh );

print qq{<h4>Welcome, ${first_name}.</h4><p>};

print q{To prepare for the first day of class, please read the paper <a href="http://sunnyday.mit.edu/papers/therac.pdf">Medical Devices: the Therac-25</a> (1995), by Nancy Leveson. We suggest reading the paper in multiple passes, to get the outline and larger points before diving in to the details. Start with a quick scan by reading the introduction, the bolded headings, and all of the figures. Scan the last section (&ldquo;Causal Factors&rdquo;). Get an idea of the larger structure and message of the paper. Then, read the paper fully from the beginning. Take notes as you read. What do you find surprising? Are there statements you disagree with? What larger points is the author trying to make?<p>};

print q{<b>Writing assignment:</b> You have been hired as an intern at a medical-device manufacturer. You receive the following memo from your boss:<p>};

print qq{<div class="well">
<b>To:</b> ${display_name}<br>
<b>From:</b> The Boss<br>
<b>Subject:</b> Request for memo re: Therac 25<br><br>

We are aware of a series of tragic incidents related to the Therac 25 linac, and curious what implications this case study may have for our own medical-device business. Please prepare a 600-word technical memo for our engineering and management staff on the following topics.<p>

<ol type="a">
<li>What should our staff know about the Therac 25 and these incidents?

<li>What is one engineering recommendation you would make to our technical staff, as a result of these incidents? <span class="text-muted">Support this recommendation with persuasive evidence.</span>

<li>What is one procedural recommendation you would make to our management staff, as a result of these incidents? <span class="text-muted">Support this recommendation with persuasive evidence.</span>
</ol>
</div><p>};

print q{Please write your memo below by noon on January 9.<p><hr><p>};

my $text = qq{<b>To:</b> The Boss<br><b>From:</b> ${display_name}<br><b>Subject:</b> Re: Request for memo re: Therac 25<br><br>[memo goes here]};
my $timestamp = q{never};

my $lastversion = $dbh->prepare( q{SELECT contents, EXTRACT(EPOCH FROM submitted) AS timestamp FROM writing WHERE sunetid = ? AND assignment = ? ORDER BY submitted DESC LIMIT 1} ) or die qq{$DBI::errstr};

$lastversion->execute( $sunetid, q{therac} ) or die qq{$DBI::errstr};

if ( my $data = $lastversion->fetchrow_hashref ) {
    $text = HTML::Entities::encode_entities( $data->{ contents }, q{'} );
    $timestamp = POSIX::strftime( q{%B %e, %I:%M %p}, localtime $data->{ timestamp } );
    $timestamp =~ s{AM}{a.m.}g;}
    $timestamp =~ s{PM}{p.m.}g;


print <<"END";
<form action='/submit' method='post'>
<input id='default' type='hidden' name='content' value='${text}'>
<trix-editor input='default'></trix-editor>
<input name='assignment' type='hidden' value='therac'><br>
<div class="col-md-4">Last saved: ${timestamp}</div>
<div class="col-md-4"></div>
<div class="col-md-4"><div align="right"><input type='submit' value='Save'></div></div>
</form>
END
    
&finish;
