#!/usr/bin/perl -w

use strict;
use DBI;

if ( scalar @ARGV != 1 ) {
  die qq{Usage: $0 CLASS\n};
}

my $class = $ARGV[ 0 ];

die unless $class eq q{CS181} or $class eq q{CS181W};

my $dbh = DBI->connect( q{dbi:Pg:dbname=cs181_spring2020} ) or die qq{$DBI::errstr};

my $adder = $dbh->prepare( q{UPDATE users SET class = ? WHERE sunetid = ?} ) or die qq{$DBI::errstr};

while ( <STDIN> ) {
  chomp;
  my @email = split /\s+/, $_;
  for ( @email ) {
    s{\,$}{}g;
    die qq{invalid email A: $_} unless m{\@stanford.edu$};
    s{\@stanford.edu$}{};
    die qq{invalid email B: $_} if m{[^a-z0-9]};

    print STDERR qq{Updating $_ -> $class...};
    $adder->execute( $class, $_ ) or die qq{$DBI::errstr};
    print STDERR qq{done.\n};
  }
}
